// Base de Datos Maestra Unificada — Casa Anglard 2026/27
// Contiene la línea de Impresión Editorial Premium y la línea de Esencias y Bienestar
const PRODUCTS = [
  // ==========================================
  // SECCIÓN A: EDICIONES IMPRESAS Y TEXTIL
  // ==========================================
  {
    id: "poster",
    name: "Póster de Exhibición",
    category: "papeleria",
    categoryLabel: "Papelería",
    medidas: "28 x 43 cm",
    material: "Papel couché 225 g",
    price: 68,
    priceText: "$68 MXN",
    img: "images/poster.jpg",
    mpLink: "" // Opcional: link express de Mercado Pago
  },
  {
    id: "postal",
    name: "Postal Editorial",
    category: "papeleria",
    categoryLabel: "Papelería",
    medidas: "15 x 10 cm",
    material: "Impresión mate premium",
    price: 41,
    priceText: "$41 MXN",
    img: "images/postal.jpg",
    mpLink: ""
  },
  {
    id: "termo",
    name: "Termo de Acero Inoxidable",
    category: "accesorios",
    categoryLabel: "Accesorios",
    medidas: "8 x 22 cm",
    material: "Acero inoxidable, impresión envolvente UV",
    price: 567,
    priceText: "$567 MXN",
    img: "images/termo.jpg",
    mpLink: ""
  },
  {
    id: "libreta",
    name: "Libreta de Cubierta Rígida",
    category: "papeleria",
    categoryLabel: "Papelería",
    medidas: "14.5 x 21 cm",
    material: "Cubierta rígida silk-touch",
    price: 189,
    priceText: "$189 MXN",
    img: "images/libreta.jpg",
    mpLink: ""
  },
  {
    id: "imanes",
    name: "Imanes de Acrílico",
    category: "accesorios",
    categoryLabel: "Accesorios",
    medidas: "7 x 7 cm / 5 x 7 cm",
    material: "Acrílico pulido de alta resistencia",
    price: 61,
    priceText: "$61 MXN",
    img: "images/imanes.jpg",
    mpLink: ""
  },
  {
    id: "lapices",
    name: "Lápices Negros Especiales",
    category: "papeleria",
    categoryLabel: "Papelería",
    medidas: "Estándar",
    material: "Con goma $20 · Sin goma $16 · Arcoíris $20",
    price: 16,
    priceText: "$16–$20 MXN",
    img: "images/lapices.jpg",
    mpLink: ""
  },
  {
    id: "pin",
    name: "Pin Metálico Esmaltado",
    category: "accesorios",
    categoryLabel: "Accesorios",
    medidas: "A definir según diseño",
    material: "Esmaltado artesanal, cotización por volumen",
    price: null,
    priceText: "Cotización",
    img: "images/pin.jpg",
    mpLink: ""
  },
  {
    id: "bolsa-chica",
    name: "Bolsa Premium Chica",
    category: "bolsas",
    categoryLabel: "Bolsas",
    medidas: "35 x 35 cm",
    material: "Tote premium lona satinada",
    price: 284,
    priceText: "$284 MXN",
    img: "images/bolsa-chica.jpg",
    mpLink: ""
  },
  {
    id: "bolsa-mediana",
    name: "Bolsa Premium Mediana",
    category: "bolsas",
    categoryLabel: "Bolsas",
    medidas: "52 x 35 cm",
    material: "Tote premium lona satinada",
    price: 338,
    priceText: "$338 MXN",
    img: "images/bolsa-mediana.jpg",
    mpLink: ""
  },
  {
    id: "bolsa-grande",
    name: "Bolsa Premium Grande",
    category: "bolsas",
    categoryLabel: "Bolsas",
    medidas: "35 x 45 cm",
    material: "Tote premium lona satinada",
    price: 311,
    priceText: "$311 MXN",
    img: "images/bolsa-grande.jpg",
    mpLink: ""
  },
  {
    id: "bolsa-manta",
    name: "Bolsa de Manta (Tote)",
    category: "bolsas",
    categoryLabel: "Bolsas",
    medidas: "40 x 40 cm",
    material: "Manta 100% natural de alta densidad",
    price: 115,
    priceText: "$115 MXN",
    img: "images/bolsa-manta.jpg",
    mpLink: ""
  },
  {
    id: "cosmetiquera",
    name: "Cosmetiquera de Mezclilla",
    category: "accesorios",
    categoryLabel: "Accesorios",
    medidas: "27 x 17 cm",
    material: "Mezclilla premium con forro y cierre",
    price: 115,
    priceText: "$115 MXN",
    img: "images/cosmetiquera.jpg",
    mpLink: ""
  },
  {
    id: "monedero",
    name: "Monedero de Mezclilla",
    category: "accesorios",
    categoryLabel: "Accesorios",
    medidas: "13.5 x 11 cm",
    material: "Tela de mezclilla con cierre reforzado",
    price: 54,
    priceText: "$54 MXN",
    img: "images/monedero.jpg",
    mpLink: ""
  },
  {
    id: "playera",
    name: "Playeras Estampadas",
    category: "textil",
    categoryLabel: "Textil",
    medidas: "Tallas CH / M / G / XG",
    material: "Algodón premium, impresión suave DTG",
    price: 270,
    priceText: "$270 / $311 MXN",
    img: "images/playera.jpg",
    mpLink: ""
  },
  {
    id: "sudadera",
    name: "Sudaderas con Capucha",
    category: "textil",
    categoryLabel: "Textil",
    medidas: "Tallas CH / M / G / XG",
    material: "Felpa de algodón, impresión suave DTG",
    price: 574,
    priceText: "$574 / $621 MXN",
    img: "images/sudadera.jpg",
    mpLink: ""
  },

  // ==========================================
  // SECCIÓN B: LÍNEA DE ÓLEOS Y ESENCIAS PURAS
  // ==========================================
  {
    id: "patchouli",
    name: "Esencia de Patchouli",
    category: "maderas",
    categoryLabel: "Esencias",
    medidas: "10 ml / 20 ml / Spray",
    material: "10ml: $250 · 20ml: $320 · Spray: $380",
    price: 250,
    priceText: "$250–$380 MXN",
    img: "images/patchouli.jpg",
    mpLink: ""
  },
  {
    id: "flor-naranjo",
    name: "Esencia de Flor de Naranjo",
    category: "maderas",
    categoryLabel: "Esencias",
    medidas: "10 ml / 20 ml / Spray",
    material: "10ml: $250 · 20ml: $320 · Spray: $380",
    price: 250,
    priceText: "$250–$380 MXN",
    img: "images/flor-naranjo.jpg",
    mpLink: ""
  },
  {
    id: "mandarina",
    name: "Esencia de Mandarina",
    category: "maderas",
    categoryLabel: "Esencias",
    medidas: "10 ml / 20 ml / Spray",
    material: "10ml: $250 · 20ml: $320 · Spray: $380",
    price: 250,
    priceText: "$250–$380 MXN",
    img: "images/mandarina.jpg",
    mpLink: ""
  },
  {
    id: "sandalo",
    name: "Esencia de Sándalo",
    category: "maderas",
    categoryLabel: "Esencias",
    medidas: "10 ml / 20 ml / Spray",
    material: "10ml: $250 · 20ml: $320 · Spray: $380",
    price: 250,
    priceText: "$250–$380 MXN",
    img: "images/sandalo.jpg",
    mpLink: ""
  },
  {
    id: "mix-18",
    name: "Mix de 18 Elementos",
    category: "maderas",
    categoryLabel: "Esencias",
    medidas: "10 ml / 20 ml / Spray",
    material: "10ml: $250 · 20ml: $320 · Spray: $380",
    price: 250,
    priceText: "$250–$380 MXN",
    img: "images/mix-18.jpg",
    mpLink: ""
  },
  {
    id: "arbol-te",
    name: "Esencia de Árbol de Té",
    category: "maderas",
    categoryLabel: "Esencias",
    medidas: "10 ml / 20 ml / Spray",
    material: "10ml: $250 · 20ml: $320 · Spray: $380",
    price: 250,
    priceText: "$250–$380 MXN",
    img: "images/arbol-te.jpg",
    mpLink: ""
  },
  {
    id: "bergamota",
    name: "Esencia de Bergamota",
    category: "maderas",
    categoryLabel: "Esencias",
    medidas: "10 ml / 20 ml / Spray",
    material: "10ml: $250 · 20ml: $320 · Spray: $380",
    price: 250,
    priceText: "$250–$380 MXN",
    img: "images/bergamota.jpg",
    mpLink: ""
  },
  {
    id: "toronja-rosa",
    name: "Esencia de Toronja Rosa",
    category: "maderas",
    categoryLabel: "Esencias",
    medidas: "10 ml / 20 ml / Spray",
    material: "10ml: $250 · 20ml: $320 · Spray: $380",
    price: 250,
    priceText: "$250–$380 MXN",
    img: "images/toronja-rosa.jpg",
    mpLink: ""
  },
  {
    id: "geranio",
    name: "Esencia de Geranio",
    category: "maderas",
    categoryLabel: "Esencias",
    medidas: "10 ml / 20 ml / Spray",
    material: "10ml: $250 · 20ml: $320 · Spray: $380",
    price: 250,
    priceText: "$250–$380 MXN",
    img: "images/geranio.jpg",
    mpLink: ""
  },
  {
    id: "menta",
    name: "Esencia de Menta",
    category: "maderas",
    categoryLabel: "Esencias",
    medidas: "10 ml / 20 ml / Spray",
    material: "10ml: $250 · 20ml: $320 · Spray: $380",
    price: 250,
    priceText: "$250–$380 MXN",
    img: "images/menta.jpg",
    mpLink: ""
  },
  {
    id: "eucalipto",
    name: "Esencia de Eucalipto",
    category: "maderas",
    categoryLabel: "Esencias",
    medidas: "10 ml / 20 ml / Spray",
    material: "10ml: $250 · 20ml: $320 · Spray: $380",
    price: 250,
    priceText: "$250–$380 MXN",
    img: "images/eucalipto.jpg",
    mpLink: ""
  },
  {
    id: "romero",
    name: "Esencia de Romero",
    category: "maderas",
    categoryLabel: "Esencias",
    medidas: "10 ml / 20 ml / Spray",
    material: "10ml: $250 · 20ml: $320 · Spray: $380",
    price: 250,
    priceText: "$250–$380 MXN",
    img: "images/romero.jpg",
    mpLink: ""
  },
  {
    id: "lavanda",
    name: "Esencia de Lavanda",
    category: "maderas",
    categoryLabel: "Esencias",
    medidas: "10 ml / 20 ml / Spray",
    material: "10ml: $250 · 20ml: $320 · Spray: $380",
    price: 250,
    priceText: "$250–$380 MXN",
    img: "images/lavanda.jpg",
    mpLink: ""
  },
  {
    id: "eucalipto-dulce",
    name: "Esencia de Eucalipto Dulce",
    category: "maderas",
    categoryLabel: "Esencias",
    medidas: "10 ml / 20 ml / Spray",
    material: "10ml: $250 · 20ml: $320 · Spray: $380",
    price: 250,
    priceText: "$250–$380 MXN",
    img: "images/eucalipto-dulce.jpg",
    mpLink: ""
  },
  {
    id: "limon",
    name: "Esencia de Limón",
    category: "maderas",
    categoryLabel: "Esencias",
    medidas: "10 ml / 20 ml / Spray",
    material: "10ml: $250 · 20ml: $320 · Spray: $380",
    price: 250,
    priceText: "$250–$380 MXN",
    img: "images/limon.jpg",
    mpLink: ""
  }
];