// Catálogo Casa Anglard 2026/27
// Precios base con el margen del +35% integrado. Incluyen IVA.
const PRODUCTS = [
  {
    id: "poster",
    name: "Póster",
    category: "papeleria",
    categoryLabel: "Papelería",
    medidas: "28 x 43 cm",
    material: "Papel couché 225 g",
    price: 68,
    priceText: "$68 MXN",
    img: "images/poster.jpg",
    mpLink: "", 
  },
  {
    id: "postal",
    name: "Postal",
    category: "papeleria",
    categoryLabel: "Papelería",
    medidas: "15 x 10 cm",
    material: "—",
    price: 41,
    priceText: "$41 MXN",
    img: "images/postal.jpg",
    mpLink: "", 
  },
  {
    id: "termo",
    name: "Termo",
    category: "accesorios",
    categoryLabel: "Accesorios",
    medidas: "8 x 22 cm",
    material: "Acero inoxidable, impresión envolvente UV",
    price: 567,
    priceText: "$567 MXN",
    img: "images/termo.jpg",
    mpLink: "", 
  },
  {
    id: "libreta",
    name: "Libreta",
    category: "papeleria",
    categoryLabel: "Papelería",
    medidas: "14.5 x 21 cm",
    material: "Cubierta rígida",
    price: 189,
    priceText: "$189 MXN",
    img: "images/libreta.jpg",
    mpLink: "", 
  },
  {
    id: "imanes",
    name: "Imanes de acrílico",
    category: "accesorios",
    categoryLabel: "Accesorios",
    medidas: "7 x 7 cm / 5 x 7 cm",
    material: "Acrílico",
    price: 61,
    priceText: "$61 MXN",
    img: "images/imanes.jpg",
    mpLink: "", 
  },
  {
    id: "lapices",
    name: "Lápices (con goma / sin goma / arcoíris)",
    category: "papeleria",
    categoryLabel: "Papelería",
    medidas: "Estándar",
    material: "Con goma $20 · Sin goma $16 · Arcoíris $20",
    price: 16,
    priceText: "$16–$20 MXN",
    img: "images/lapices.jpg",
    mpLink: "", 
  },
  {
    id: "pin",
    name: "Pin metálico",
    category: "accesorios",
    categoryLabel: "Accesorios",
    medidas: "A definir",
    material: "Esmaltado, cotización por proyecto",
    price: null,
    priceText: "Cotización",
    img: "images/pin.jpg",
    mpLink: "", 
  },
  {
    id: "bolsa-chica",
    name: "Bolsa premium chica",
    category: "bolsas",
    categoryLabel: "Bolsas",
    medidas: "35 x 35 cm",
    material: "Tote premium",
    price: 284,
    priceText: "$284 MXN",
    img: "images/bolsa-chica.jpg",
    mpLink: "", 
  },
  {
    id: "bolsa-mediana",
    name: "Bolsa premium mediana",
    category: "bolsas",
    categoryLabel: "Bolsas",
    medidas: "52 x 35 cm",
    material: "Tote premium",
    price: 338,
    priceText: "$338 MXN",
    img: "images/bolsa-mediana.jpg",
    mpLink: "", 
  },
  {
    id: "bolsa-grande",
    name: "Bolsa premium grande",
    category: "bolsas",
    categoryLabel: "Bolsas",
    medidas: "35 x 45 cm",
    material: "Tote premium",
    price: 311,
    priceText: "$311 MXN",
    img: "images/bolsa-grande.jpg",
    mpLink: "", 
  },
  {
    id: "bolsa-manta",
    name: "Bolsa de manta (tote)",
    category: "bolsas",
    categoryLabel: "Bolsas",
    medidas: "40 x 40 cm",
    material: "Manta natural",
    price: 115,
    priceText: "$115 MXN",
    img: "images/bolsa-manta.jpg",
    mpLink: "", 
  },
  {
    id: "cosmetiquera",
    name: "Cosmetiquera de mezclilla",
    category: "accesorios",
    categoryLabel: "Accesorios",
    medidas: "27 x 17 cm",
    material: "Mezclilla, cierre",
    price: 115,
    priceText: "$115 MXN",
    img: "images/cosmetiquera.jpg",
    mpLink: "", 
  },
  {
    id: "monedero",
    name: "Monedero de mezclilla",
    category: "accesorios",
    categoryLabel: "Accesorios",
    medidas: "13.5 x 11 cm",
    material: "Tela con cierre",
    price: 54,
    priceText: "$54 MXN",
    img: "images/monedero.jpg",
    mpLink: "", 
  },
  {
    id: "playera",
    name: "Playeras (blanca / color)",
    category: "textil",
    categoryLabel: "Textil",
    medidas: "Tallas CH / M / G / XG",
    material: "DTG",
    price: 270,
    priceText: "$270 / $311 MXN",
    img: "images/playera.jpg",
    mpLink: "", 
  },
  {
    id: "sudadera",
    name: "Sudaderas (blanca / color)",
    category: "textil",
    categoryLabel: "Textil",
    medidas: "Tallas CH / M / G / XG",
    material: "Algodón, DTG",
    price: 574,
    priceText: "$574 / $621 MXN",
    img: "images/sudadera.jpg",
    mpLink: "", 
  },
];